name = "saare-api"
main = "src/index.js"
compatibility_date = "2026-08-17"

[vars]
CORS_ORIGIN = "*"
ENVIRONMENT = "production"
STRIPE_WEBHOOK_SECRET = "whsec_YOUR_STRIPE_WEBHOOK_SECRET"
PRIMARY_AUDITOR = "alfonsosb1@gmail.com"