name: Delete Untagged GHCR Images

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  clean-untagged:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Delete untagged images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'saare-sidecar'
          package-type: 'container'
          min-versions-to-keep: 3
          delete-only-untagged: true
